### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by elifbuyukorhan** [alexandrosstergiou/TrajREC#1]
Hi, 
I've downloaded your repo and dataset but I cannot run the command you write in README file. (usage section) 
The command: 
$ python run.py --trajectories data/HR-ShanghaiTech/training/trajectories-corrected/00 --testdata data/HR-ShanghaiTech/testing --batch_size 512 --wandb False

I got: 
command not found

I realize that your parser code snippet does not have --testdata command. This issue may be about this.

**Comment by alexandrosstergiou** [comment]
Hi @elifbuyukorhan ,

Would be best to quote any directories/paths at the command line so they are parsed as a whole. 

`testdata` is defined at [`#L357`](https://github.com/alexandrosstergiou/TrajREC/blob/79be6ebd888513fa05616bca7801300b17b50728/run.py#L357)
