### ISSUE TITLE
KeyError: 'bb_scaler'

### ISSUE THREAD

**Issue by lihuining** [alexandrosstergiou/TrajREC#3]
I downloaded the best model and used this script,python generate_reconstructions.py --trajectories data/HR-ShanghaiTech/testing/ --chkp /media/allenyljiang/564AFA804AFA5BE5/Codes/TrajREC/checkpoints/HRSTC_ckpt.pt, and then encountered the key error, can any one tell me how to avoid this error?

**Comment by alexandrosstergiou** [comment]
Hi @lihuining ,

You can get all `"xx_scaler"` arguments by calling the `create_train_val_v2` from `dataloader.py` [#L104](https://github.com/alexandrosstergiou/TrajREC/blob/79be6ebd888513fa05616bca7801300b17b50728/dataloader.py#L104)

You can use the same call as in [#L8-90](https://github.com/alexandrosstergiou/TrajREC/blob/79be6ebd888513fa05616bca7801300b17b50728/run.py#L89-L90) in `run.py`
